spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      properties:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSLDialect
  mail:
    host: localhost
    port: 1025
    username: postgres
    password: postgres
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
          connectiontimout: 500
          timeout: 3000
          writetimeout: 5000

  application:
    security:
      jwt:
        secret-key: very_long_and_secure_and_safe_access_key
        expiration: 36000000

    server:
      8081