server.port=8081
server.error.include-message=always
spring.datasource.url=jdbc:postgresql://localhost:5432/estage
spring.datasource.username=postgres
spring.datasource.password=postgres
logging.level.web=DEBUG        

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=0.0.0.0
spring.mail.port=1025

spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB

# JWT secret key
jwt.secret=very_long_and_secure_and_safe_access_key
# Access token lifespan (5 min)
jwt.jwtExp=36000000
# Refresh token lifespan (24 hours)
jwt.refreshExp=86400000

application.security.allowed-origins=http://localhost:8000
application.fontend.default-url=http://localhost:8000

#context-path: /api/swagger
